- name: configuring redis repository
  ansible.builtin.copy:
    src: repos.yml
    dest: /etc/yum.repos.d/redis.repo

- name: installing redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Updating redis config file
  ansible.builtin.replace:
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    path: /etc/redis.conf


- name: starting redis
  ansible.builtin.systemd:
    name: redis
    enabled: yes
    state: restarted