#- name: Confgure repository for mongodb
#  ansible.builtin.get_url:
#    url: https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo
#    dest: /etc/yum.repos.d/mongodb.repo

- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Supports a validate command
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


- name: Update mongodb configuration - update listen ip
  lineinfile:
    path: /etc/mongod.conf
    search_string: '127.0.0.1'
    line: 0.0.0.0

- name: Start mongodb
  ansible.builtin.systemd:
    state: restarted
    name: mongod
    enabled: yes

#- name: Download and extract schemas
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
#    dest: /tmp/
#    remote_src: yes

- name: locad schemas
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
    loop:
      - catalogue
      - users

- name: Download and extract mongodb
  include_role:
    name: common
    tasks_from: download

#- name: load catalog schema
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/catalogue.js"
#    idempotent: yes
##if schema is there it will not create
#  register: out
#
#- name: load users schema
#  community.mongodb.mongodb_shell:
#    file: "/tmp/mongodb-main/users.js"
#    idempotent: yes
#  #if schema is there it will not create
#  register: out
#- debug:
#    msg: out


