#If we declare the variable at play level all the tasks will accept the variable.

- name: play level variables
  hosts: prd
  vars:
    url: chakra.pizza.com
  tasks:
    - name: prind URL
      ansible.builtin.debug:
        msg: url = {{url}}

 #Task level variable, scope of the variable is only for this task.
    - name: print task level URL
      vars:
        url: google.com
      ansible.builtin.debug:
          msg: url = {{url}}
    - name: print task level URL
      ansible.builtin.debug:
        msg: url = {{url}}

#Variables from a file.
- name: play level variables
  hosts: prd
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print variables from file
      ansible.builtin.debug:
        msg: url = {{url}}

- name: inventory level variables
  hosts: prd
  tasks:
    - name: prind URL
      ansible.builtin.debug:
        msg: url = {{url}}

#command level variable is using -e option
#gp; ansible-playbook -i inventory-sample 02-vars.yml -e url=example.com -ucentos -k
