- name: install python gcc python3-devel
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel

- name: Add application user
  include_role:
    name: common
    tasks_from: user

- name: Download and extract {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
  become_user: roboshop

- name: cleanup old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Install app content
  ansible.builtin.copy:
     src: /tmp/"{{COMPONENT}}-main"/
     dest: /home/roboshop/{{COMPONENT}}/

- name: install dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /home/roboshop/{{COMPONENT}}


#- name: Install bottle for Python 3.3 specifically, using the 'pip3.3' executable
#  pip:
#    requirements: /home/roboshop/payment/requirements.txt
#    executable: pip3



