- name: configure repose for {{COMPONENT}}
  ansible.builtin.copy:
    src: "{{COMPONENT}}_repos"
    dest: /etc/yum.repos.d/mysql.repo

- name: "installing {{COMPONENT}} server"
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: installed


- name: "starting {{COMPONENT}} server"
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: check db password by collecting information
  community.mysql.mysql_info:
    login_user: RoboShop@1
  register: mysql_state
  ignore_errors: yes

#- debug:
#    msg: "{{mysql_state}}"

- name: "reset {{COMPONENT}} password"
  when: mysql_state.failed
  debug:
    msg: "{{mysql_state}}"