- name: configure repose for {{COMPONENT}}
  ansible.builtin.copy:
    src: "{{COMPONENT}}"_repos
    dest: /etc/yum.repos.d/mysql.repo


- name: Update service file of {{COMPONENT}}
  ansible.builtin.copy:
    src: "{{ COMPONENT }}.service"
    dest:  /etc/systemd/system/{{COMPONENT}}.service

- name: "installing {{COMPONENT}} server"
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed


- name: "starting {{COMPONENT}} server"
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes