- name: configure repose for {{COMPONENT}}
  ansible.builtin.copy:
    src: "{{COMPONENT}}_repos"
    dest: /etc/yum.repos.d/mysql.repo

- name: "installing {{COMPONENT}} server"
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed


- name: "starting {{COMPONENT}} server"
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: check db password by collecting information
  community.mysql.mysql_info:
    login_user: RoboShop@1